HOME_DIR: "/project/ReadStatistics-data/Snakemake/" # where your codes and snakefile sits.

FILES_DIR: "BAM_FILES/" # The directory where the bam files live.
MODEL_DIR: "MODELS/" # The directory of the machine learning model to predict methylation state of CpG 
                                                            # Islands
OUTPUT_DIR: "OUTPUT/" # The directory where the output files are stored at.
PYTHON_DIR: "PYTHON/" # The directory of the python files

FASTA_FILE_DIR: "OTHER_FILES/GRCh38_full_analysis_set_plus_decoy_hla.fa" #Fasta file
CpG_ISL_BED_FILE_DIR: "OTHER_FILES/CpG_isl_hg38.bed" # Bed file of the CpG islands
REMOVE_READS_DIR: "OTHER_FILES/remove_reads.bed" # Remove reads which are bad

TXT_FILE_DIR: "file_links.txt" # The file which contains the links to the bam files