HOME_DIR: "C:/Users/HP/OneDrive/Documents/GitHub/MethylationPrediction/" # where your codes and snakefile sits.

FILES_DIR: "bam_files/" # The directory where the bam files live.
MODEL_DIR: "workflow/rules/" # The directory of the machine learning model to predict methylation state of CpG Islands
OUTPUT_DIR: "output" # The directory where the output files are stored at.
PYTHON_DIR: "workflow/scripts/" # The directory of the python files

FASTA_FILE_DIR: "resources/GRCh38_full_analysis_set_plus_decoy_hla.fa" #Fasta file
CpG_ISL_BED_FILE_DIR: "resources/CpG_isl_hg38.bed" # Bed file of the CpG islands
REMOVE_READS_DIR: "resources/remove_reads.bed" # Remove reads which are bad

TXT_FILE_DIR: "config/file_links.txt" # The file which contains the links to the bam files
MODEL_FILE: "workflow/models/trained_model.joblib"