HOME_DIR: "/path/to/MethylationPrediction/" # where your codes and snakefile sits.

FILES_DIR: "bam_files/" # The directory where the bam files live.
MODEL_DIR: "workflow/models/" # The directory with the machine learning model to predict methylation state of CpG Islands or where to save the model in training mode.
OUTPUT_DIR: "results/" # The directory where the output files are stored at.
PYTHON_DIR: "workflow/scripts/" # The directory of the python files

FASTA_FILE_DIR: "resources/GRCh38_full_analysis_set_plus_decoy_hla.fa" # Genome fasta file
CpG_ISL_BED_FILE_DIR: "resources/CpG_isl_hg38.bed" # Bed file with CpG islands coordinates
REMOVE_READS_DIR: "resources/remove_reads.bed" # Remove reads which are bad

TXT_FILE_DIR: "config/file_links_local.txt" # The file with paths/url links to input bam files (proceeded in parallel)
FASTA_FILE_LINK: "http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/GRCh38_reference_genome/GRCh38_full_analysis_set_plus_decoy_hla.fa" # Link to the fasta file (if no local reference provided)
METHYLATION_ANNOTATION_DIR: "resources/hg38_methylation_lymph_CL.bed" # The bed file which contains the methylation state of the CpG islands. Here we use methylation states of Lymphoblastoid cell line, but one can use other tissues to train the model.

MODE: "predict" # Can be "train" or "predict" mode. If "train" is used, the model is trained and saved. If "predict" - the model will be loaded and used to predict the methylation state of the CpG islands.
